export * from './branches.service';
import { BranchesService } from './branches.service';
export * from './companies.service';
import { CompaniesService } from './companies.service';
export * from './dashboard.service';
import { DashboardService } from './dashboard.service';
export * from './groups.service';
import { GroupsService } from './groups.service';
export * from './products.service';
import { ProductsService } from './products.service';
export * from './session.service';
import { SessionService } from './session.service';
export * from './settings.service';
import { SettingsService } from './settings.service';
export * from './shippingmethods.service';
import { ShippingmethodsService } from './shippingmethods.service';
export * from './users.service';
import { UsersService } from './users.service';
export * from './variations.service';
import { VariationsService } from './variations.service';
export const APIS = [BranchesService, CompaniesService, DashboardService, GroupsService, ProductsService, SessionService, SettingsService, ShippingmethodsService, UsersService, VariationsService];
