export * from './branches.service';
import { BranchesService } from './branches.service';
export * from './categories.service';
import { CategoriesService } from './categories.service';
export * from './companies.service';
import { CompaniesService } from './companies.service';
export * from './dashboard.service';
import { DashboardService } from './dashboard.service';
export * from './groups.service';
import { GroupsService } from './groups.service';
export * from './orders.service';
import { OrdersService } from './orders.service';
export * from './orderslines.service';
import { OrderslinesService } from './orderslines.service';
export * from './pizzacategories.service';
import { PizzacategoriesService } from './pizzacategories.service';
export * from './pizzas.service';
import { PizzasService } from './pizzas.service';
export * from './pizzavariations.service';
import { PizzavariationsService } from './pizzavariations.service';
export * from './productcategories.service';
import { ProductcategoriesService } from './productcategories.service';
export * from './products.service';
import { ProductsService } from './products.service';
export * from './productvariations.service';
import { ProductvariationsService } from './productvariations.service';
export * from './registration.service';
import { RegistrationService } from './registration.service';
export * from './session.service';
import { SessionService } from './session.service';
export * from './settings.service';
import { SettingsService } from './settings.service';
export * from './shippingmethods.service';
import { ShippingmethodsService } from './shippingmethods.service';
export * from './toppingextras.service';
import { ToppingextrasService } from './toppingextras.service';
export * from './users.service';
import { UsersService } from './users.service';
export const APIS = [BranchesService, CategoriesService, CompaniesService, DashboardService, GroupsService, OrdersService, OrderslinesService, PizzacategoriesService, PizzasService, PizzavariationsService, ProductcategoriesService, ProductsService, ProductvariationsService, RegistrationService, SessionService, SettingsService, ShippingmethodsService, ToppingextrasService, UsersService];
