/**
 * PizzaShop
 * <h1>REST API for managing a pizzeria.</h1> <br>  The application includes the management of:  <ul>     <li>users (workers and customers)</li>     <li>company branches</li>     <li>products (variations like doughs, dimensions and toppings, categories)</li>     <li>orders (creation, management)</li> <ul>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: gianluca.fattarsi@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { ToppingExtra } from '../model/toppingExtra';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class ToppingextrasService {

    protected basePath = 'https://virtserver.swaggerhub.com/fattazzo/pizza-shop/1.0.0';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Get a ToppingExtra
     * Gets the details of a single instance of a &#x60;ToppingExtra&#x60;.
     * @param toppingextraId A unique identifier for a &#x60;ToppingExtra&#x60;.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getToppingExtra(toppingextraId: number, observe?: 'body', reportProgress?: boolean): Observable<ToppingExtra>;
    public getToppingExtra(toppingextraId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ToppingExtra>>;
    public getToppingExtra(toppingextraId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ToppingExtra>>;
    public getToppingExtra(toppingextraId: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (toppingextraId === null || toppingextraId === undefined) {
            throw new Error('Required parameter toppingextraId was null or undefined when calling getToppingExtra.');
        }

        let headers = this.defaultHeaders;

        // authentication (BearerAuth) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<ToppingExtra>('get',`${this.basePath}/toppingextras/${encodeURIComponent(String(toppingextraId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * List All ToppingExtras
     * Gets a list of all &#x60;ToppingExtra&#x60; entities.
     * @param doughId Work with &#x60;sizeId&#x60; parameter
     * @param sizeId Work with &#x60;doughId&#x60; parameter
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getToppingExtras(doughId?: number, sizeId?: number, observe?: 'body', reportProgress?: boolean): Observable<Array<ToppingExtra>>;
    public getToppingExtras(doughId?: number, sizeId?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<ToppingExtra>>>;
    public getToppingExtras(doughId?: number, sizeId?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<ToppingExtra>>>;
    public getToppingExtras(doughId?: number, sizeId?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {



        let headers = this.defaultHeaders;
        if (doughId !== undefined && doughId !== null) {
            headers = headers.set('doughId', String(doughId));
        }
        if (sizeId !== undefined && sizeId !== null) {
            headers = headers.set('sizeId', String(sizeId));
        }

        // authentication (BearerAuth) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<ToppingExtra>>('get',`${this.basePath}/toppingextras`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Update a ToppingExtra
     * Updates an existing &#x60;ToppingExtra&#x60;.
     * @param body Updated &#x60;ToppingExtra&#x60; information.
     * @param toppingextraId A unique identifier for a &#x60;ToppingExtra&#x60;.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateToppingExtra(body: ToppingExtra, toppingextraId: number, observe?: 'body', reportProgress?: boolean): Observable<ToppingExtra>;
    public updateToppingExtra(body: ToppingExtra, toppingextraId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ToppingExtra>>;
    public updateToppingExtra(body: ToppingExtra, toppingextraId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ToppingExtra>>;
    public updateToppingExtra(body: ToppingExtra, toppingextraId: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling updateToppingExtra.');
        }

        if (toppingextraId === null || toppingextraId === undefined) {
            throw new Error('Required parameter toppingextraId was null or undefined when calling updateToppingExtra.');
        }

        let headers = this.defaultHeaders;

        // authentication (BearerAuth) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<ToppingExtra>('put',`${this.basePath}/toppingextras/${encodeURIComponent(String(toppingextraId))}`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Update All ToppingExtras
     * Updates existing &#x60;ToppingExtra&#x60;.
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateToppingExtras(body: Array<ToppingExtra>, observe?: 'body', reportProgress?: boolean): Observable<Array<ToppingExtra>>;
    public updateToppingExtras(body: Array<ToppingExtra>, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<ToppingExtra>>>;
    public updateToppingExtras(body: Array<ToppingExtra>, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<ToppingExtra>>>;
    public updateToppingExtras(body: Array<ToppingExtra>, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling updateToppingExtras.');
        }

        let headers = this.defaultHeaders;

        // authentication (BearerAuth) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<Array<ToppingExtra>>('put',`${this.basePath}/toppingextras`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
