/**
 * PizzaShop
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { Dough } from '../model/dough';
import { Size } from '../model/size';
import { Topping } from '../model/topping';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class VariationsService {

    protected basePath = 'https://virtserver.swaggerhub.com/fattazzo/pizza-shop/1.0.0';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Create a Dough
     * Creates a new instance of a &#x60;Dough&#x60;.
     * @param body A new &#x60;Dough&#x60; to be created.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createDough(body: Dough, observe?: 'body', reportProgress?: boolean): Observable<Dough>;
    public createDough(body: Dough, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Dough>>;
    public createDough(body: Dough, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Dough>>;
    public createDough(body: Dough, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling createDough.');
        }

        let headers = this.defaultHeaders;

        // authentication (Authentication) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<Dough>('post',`${this.basePath}/variations/doughs`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Create a Size
     * Creates a new instance of a &#x60;Size&#x60;.
     * @param body A new &#x60;Size&#x60; to be created.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createSize(body: Size, observe?: 'body', reportProgress?: boolean): Observable<Size>;
    public createSize(body: Size, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Size>>;
    public createSize(body: Size, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Size>>;
    public createSize(body: Size, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling createSize.');
        }

        let headers = this.defaultHeaders;

        // authentication (Authentication) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<Size>('post',`${this.basePath}/variations/sizes`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Create a Topping
     * Creates a new instance of a &#x60;Topping&#x60;.
     * @param body A new &#x60;Topping&#x60; to be created.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createTopping(body: Topping, observe?: 'body', reportProgress?: boolean): Observable<Topping>;
    public createTopping(body: Topping, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Topping>>;
    public createTopping(body: Topping, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Topping>>;
    public createTopping(body: Topping, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling createTopping.');
        }

        let headers = this.defaultHeaders;

        // authentication (Authentication) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<Topping>('post',`${this.basePath}/variations/toppings`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Delete a Dough
     * Deletes an existing &#x60;Dough&#x60;.
     * @param doughId A unique identifier for a &#x60;Dough&#x60;.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteDough(doughId: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public deleteDough(doughId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public deleteDough(doughId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public deleteDough(doughId: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (doughId === null || doughId === undefined) {
            throw new Error('Required parameter doughId was null or undefined when calling deleteDough.');
        }

        let headers = this.defaultHeaders;

        // authentication (Authentication) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('delete',`${this.basePath}/variations/doughs/${encodeURIComponent(String(doughId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Delete a Size
     * Deletes an existing &#x60;Size&#x60;.
     * @param sizeId A unique identifier for a &#x60;Size&#x60;.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteSize(sizeId: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public deleteSize(sizeId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public deleteSize(sizeId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public deleteSize(sizeId: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (sizeId === null || sizeId === undefined) {
            throw new Error('Required parameter sizeId was null or undefined when calling deleteSize.');
        }

        let headers = this.defaultHeaders;

        // authentication (Authentication) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('delete',`${this.basePath}/variations/sizes/${encodeURIComponent(String(sizeId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Delete a Topping
     * Deletes an existing &#x60;Topping&#x60;.
     * @param toppingId A unique identifier for a &#x60;Topping&#x60;.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteTopping(toppingId: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public deleteTopping(toppingId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public deleteTopping(toppingId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public deleteTopping(toppingId: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (toppingId === null || toppingId === undefined) {
            throw new Error('Required parameter toppingId was null or undefined when calling deleteTopping.');
        }

        let headers = this.defaultHeaders;

        // authentication (Authentication) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('delete',`${this.basePath}/variations/toppings/${encodeURIComponent(String(toppingId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get a Dough
     * Gets the details of a single instance of a &#x60;Dough&#x60;.
     * @param doughId A unique identifier for a &#x60;Dough&#x60;.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getDough(doughId: number, observe?: 'body', reportProgress?: boolean): Observable<Dough>;
    public getDough(doughId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Dough>>;
    public getDough(doughId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Dough>>;
    public getDough(doughId: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (doughId === null || doughId === undefined) {
            throw new Error('Required parameter doughId was null or undefined when calling getDough.');
        }

        let headers = this.defaultHeaders;

        // authentication (Authentication) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Dough>('get',`${this.basePath}/variations/doughs/${encodeURIComponent(String(doughId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * List All doughs
     * Gets a list of all &#x60;Dough&#x60; entities.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getDoughs(observe?: 'body', reportProgress?: boolean): Observable<Array<Dough>>;
    public getDoughs(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Dough>>>;
    public getDoughs(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Dough>>>;
    public getDoughs(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // authentication (Authentication) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<Dough>>('get',`${this.basePath}/variations/doughs`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get a Size
     * Gets the details of a single instance of a &#x60;Size&#x60;.
     * @param sizeId A unique identifier for a &#x60;Size&#x60;.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getSize(sizeId: number, observe?: 'body', reportProgress?: boolean): Observable<Size>;
    public getSize(sizeId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Size>>;
    public getSize(sizeId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Size>>;
    public getSize(sizeId: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (sizeId === null || sizeId === undefined) {
            throw new Error('Required parameter sizeId was null or undefined when calling getSize.');
        }

        let headers = this.defaultHeaders;

        // authentication (Authentication) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Size>('get',`${this.basePath}/variations/sizes/${encodeURIComponent(String(sizeId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * List All sizes
     * Gets a list of all &#x60;Size&#x60; entities.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getSizes(observe?: 'body', reportProgress?: boolean): Observable<Array<Size>>;
    public getSizes(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Size>>>;
    public getSizes(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Size>>>;
    public getSizes(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // authentication (Authentication) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<Size>>('get',`${this.basePath}/variations/sizes`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get a Topping
     * Gets the details of a single instance of a &#x60;Topping&#x60;.
     * @param toppingId A unique identifier for a &#x60;Topping&#x60;.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getTopping(toppingId: number, observe?: 'body', reportProgress?: boolean): Observable<Topping>;
    public getTopping(toppingId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Topping>>;
    public getTopping(toppingId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Topping>>;
    public getTopping(toppingId: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (toppingId === null || toppingId === undefined) {
            throw new Error('Required parameter toppingId was null or undefined when calling getTopping.');
        }

        let headers = this.defaultHeaders;

        // authentication (Authentication) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Topping>('get',`${this.basePath}/variations/toppings/${encodeURIComponent(String(toppingId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * List All toppings
     * Gets a list of all &#x60;Topping&#x60; entities.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getToppings(observe?: 'body', reportProgress?: boolean): Observable<Array<Topping>>;
    public getToppings(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Topping>>>;
    public getToppings(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Topping>>>;
    public getToppings(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // authentication (Authentication) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<Topping>>('get',`${this.basePath}/variations/toppings`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Update a Dough
     * Updates an existing &#x60;Dough&#x60;.
     * @param body Updated &#x60;Dough&#x60; information.
     * @param doughId A unique identifier for a &#x60;Dough&#x60;.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateDough(body: Dough, doughId: number, observe?: 'body', reportProgress?: boolean): Observable<Dough>;
    public updateDough(body: Dough, doughId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Dough>>;
    public updateDough(body: Dough, doughId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Dough>>;
    public updateDough(body: Dough, doughId: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling updateDough.');
        }

        if (doughId === null || doughId === undefined) {
            throw new Error('Required parameter doughId was null or undefined when calling updateDough.');
        }

        let headers = this.defaultHeaders;

        // authentication (Authentication) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<Dough>('put',`${this.basePath}/variations/doughs/${encodeURIComponent(String(doughId))}`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Update a Size
     * Updates an existing &#x60;Size&#x60;.
     * @param body Updated &#x60;Size&#x60; information.
     * @param sizeId A unique identifier for a &#x60;Size&#x60;.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateSize(body: Size, sizeId: number, observe?: 'body', reportProgress?: boolean): Observable<Size>;
    public updateSize(body: Size, sizeId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Size>>;
    public updateSize(body: Size, sizeId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Size>>;
    public updateSize(body: Size, sizeId: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling updateSize.');
        }

        if (sizeId === null || sizeId === undefined) {
            throw new Error('Required parameter sizeId was null or undefined when calling updateSize.');
        }

        let headers = this.defaultHeaders;

        // authentication (Authentication) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<Size>('put',`${this.basePath}/variations/sizes/${encodeURIComponent(String(sizeId))}`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Update a Topping
     * Updates an existing &#x60;Topping&#x60;.
     * @param body Updated &#x60;Topping&#x60; information.
     * @param toppingId A unique identifier for a &#x60;Topping&#x60;.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateTopping(body: Topping, toppingId: number, observe?: 'body', reportProgress?: boolean): Observable<Topping>;
    public updateTopping(body: Topping, toppingId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Topping>>;
    public updateTopping(body: Topping, toppingId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Topping>>;
    public updateTopping(body: Topping, toppingId: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling updateTopping.');
        }

        if (toppingId === null || toppingId === undefined) {
            throw new Error('Required parameter toppingId was null or undefined when calling updateTopping.');
        }

        let headers = this.defaultHeaders;

        // authentication (Authentication) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<Topping>('put',`${this.basePath}/variations/toppings/${encodeURIComponent(String(toppingId))}`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
