/**
 * PizzaShop
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Address } from './address';
import { Branch } from './branch';
import { ShippingMethod } from './shippingMethod';
import { ShippingZone } from './shippingZone';

export interface BranchDetails extends Branch { 
    /**
     * List of available `ShippingMethod`
     */
    shippingMethods: Array<ShippingMethod>;
    /**
     * List of available `ShippingZone`
     */
    shippingZones?: Array<ShippingZone>;
}