/**
 * PizzaShop
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Company { 
    /**
     * Unique identifier
     */
    id?: number;
    /**
     * Company name
     */
    name: string;
    /**
     * Company web url
     */
    webUrl?: string;
    /**
     * Url of `Company` logo
     */
    logoUrl?: string;
}