/**
 * PizzaShop
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Dough } from './dough';
import { Product } from './product';
import { ProductCategory } from './productCategory';
import { Size } from './size';
import { ToppingExtra } from './toppingExtra';

export interface ProductDetails extends Product { 
    readonly doughs?: Array<Dough>;
    readonly sizes?: Array<Size>;
    readonly toppingExtras?: Array<ToppingExtra>;
}