/**
 * PizzaShop
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Dough } from './dough';
import { ProductCategory } from './productCategory';
import { Size } from './size';

export interface ProductCategoryDetails extends ProductCategory { 
    doughs?: Array<Dough>;
    sizes?: Array<Size>;
}