/**
 * PizzaShop
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type Role = 'WEB_ADMIN' | 'SECURITY_VIEW' | 'SECURITY_EDIT';

export const Role = {
    WEBADMIN: 'WEB_ADMIN' as Role,
    SECURITYVIEW: 'SECURITY_VIEW' as Role,
    SECURITYEDIT: 'SECURITY_EDIT' as Role
};