/**
 * PizzaShop
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type Role = 'WEB_ADMIN' | 'SECURITY' | 'SHIPPING_METHODS' | 'COMPANY' | 'EDIT_ACCOUNT' | 'VARIATIONS' | 'PRODUCTS';

export const Role = {
    WEBADMIN: 'WEB_ADMIN' as Role,
    SECURITY: 'SECURITY' as Role,
    SHIPPINGMETHODS: 'SHIPPING_METHODS' as Role,
    COMPANY: 'COMPANY' as Role,
    EDITACCOUNT: 'EDIT_ACCOUNT' as Role,
    VARIATIONS: 'VARIATIONS' as Role,
    PRODUCTS: 'PRODUCTS' as Role
};