/**
 * PizzaShop
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ShippingMethodType } from './shippingMethodType';

export interface ShippingMethod { 
    /**
     * Method ID
     */
    id?: number;
    /**
     * Shipping method title
     */
    title: string;
    /**
     * Shipping method description
     */
    description?: string;
    type: ShippingMethodType;
    enabled: boolean;
}