/**
 * PizzaShop
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type ShippingMethodType = 'PAY_PAL' | 'CASH_ON_DELIVERY';

export const ShippingMethodType = {
    PAYPAL: 'PAY_PAL' as ShippingMethodType,
    CASHONDELIVERY: 'CASH_ON_DELIVERY' as ShippingMethodType
};