/**
 * PizzaShop
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Dough } from './dough';
import { Size } from './size';
import { Topping } from './topping';

/**
 * Price of the topping based on a dough and size
 */
export interface ToppingExtra { 
    id?: number;
    topping: Topping;
    dough: Dough;
    size: Size;
    extra: number;
    enabled: boolean;
}