/**
 * PizzaShop
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DeliveryAddress } from './deliveryAddress';
import { Group } from './group';
import { User } from './user';

export interface UserDetails extends User { 
    /**
     * List of assigned `Group`
     */
    groups: Array<Group>;
    /**
     * List of delivery address
     */
    deliveryAddresses?: Array<DeliveryAddress>;
}