/**
 * PizzaShop
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { UserStatus } from './userStatus';
import { UserType } from './userType';

export interface User { 
    /**
     * Login name
     */
    username: string;
    /**
     * The email address
     */
    email?: string;
    /**
     * Read only users cannot be deleted
     */
    readOnly: boolean;
    type: UserType;
    status: UserStatus;
}