/**
 * PizzaShop
 * <h1>REST API for managing a pizzeria.</h1> <br>  The application includes the management of:  <ul>     <li>users (workers and customers)</li>     <li>company branches</li>     <li>products (variations like doughs, dimensions and toppings, categories)</li>     <li>orders (creation, management)</li> <ul>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: gianluca.fattarsi@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DeliveryAddress } from './deliveryAddress';
import { Group } from './group';
import { User } from './user';
import { UserStatus } from './userStatus';
import { UserType } from './userType';

export interface UserDetails extends User { 
    /**
     * Login password
     */
    password?: string;
    /**
     * First name
     */
    firstName?: string;
    /**
     * Last name
     */
    lastName?: string;
    /**
     * List of assigned `Group`
     */
    groups: Array<Group>;
    /**
     * List of delivery address
     */
    deliveryAddresses?: Array<DeliveryAddress>;
}